export const
    CREATE_ARROWS = 'CREATE_ARROWS',
    CREATE_MAIN_CONTAINER = 'CREATE_MAIN_CONTAINER',
    CREATE_SLIDES = 'CREATE_SLIDES',
    CREATE_BREADCRUMBS = 'CREATE_BREADCRUMBS',
    CREATE_DATA_NOT_FOUND = 'CREATE_DATA_NOT_FOUND',

    SET_OPTIONS = 'SET_OPTIONS',
    SET_SLIDES = 'SET_SLIDES',
    SET_BREADCRUMBS = 'SET_BREADCRUMBS',

    DISPLAY_SLIDE = 'DISPLAY_SLIDE',

    SET_TIMER = 'SET_TIMER';
